### ISSUE TITLE
Can't install lxml-cffi in virtualenv

### ISSUE THREAD

**Issue by kvdveer** [lxml-cffi/lxml-cffi#2]
When I create a pypy virtualenv, installing lxml-cffi fails:

```
/tmp # virtualenv -p /usr/bin/pypy pypyenv 
/tmp # . pypyenv/bin/activate
/tmp (pypyenv) # python --version
Python 2.7.10 (4.0.1+dfsg-1~ppa1~ubuntu15.04, Nov 20 2015, 19:34:27)
[PyPy 4.0.1 with GCC 4.9.2]
/tmp (pypyenv) # pip install git+https://github.com/lxml-cffi/lxml-cffi.git
Collecting git+https://github.com/lxml-cffi/lxml-cffi.git
  Cloning https://github.com/lxml-cffi/lxml-cffi.git to ./pip-DmEQEX-build
    Complete output from command python setup.py egg_info:
    error in lxml-cffi setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
    Building lxml version 3.4.0.1.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-DmEQEX-build
```

I'm using the [official pypy PPA](https://launchpad.net/~pypy/+archive/ubuntu/ppa) on ubuntu 15.10

**Comment by mithrandi** [comment]
You'll need a newer version of setuptools; try `pip install --upgrade pip setuptools` in the virtualenv first. Let me know if that doesn't do the trick.

(Note that I have uploaded a release to pypi, so you can just `pip install lxml-cffi` without a git checkout.)

**Comment by kvdveer** [comment]
Hi Tristan,

Thanks for the quick reply. Upgrading pip & setuptools did the job.

You may want to add this to the Readme or some other documentation - I'm
not going to be the only one who tries to start with a clean version of
pip/setuptools in their CI. ;-)
